[book]
authors = ["auking45"]
language = "en"
multilingual = false
src = "src"
title = "Be Better Rustacean"

[output.html.fold]
enable = true   # whether or not to enable section folding
level = 0       # the depth to start folding
